[build]
  base    = ""
  publish = "public"
  command = "hugo"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.133.1"
[context.production.environment]
  HUGO_VERSION = "0.133.1"
  
[[headers]]
  for = "/Assemblies-Naked-Punch.pdf"
  [headers.values]
    X-Robots-Tag = "noindex"